import { useEffect, useState } from 'react'
import api from '../api/client'

interface AnalyticsData { has_data: boolean; sprint?: string; completion_pct: number; current_scope: number; completed_sp: number; remaining_sp: number; day1_fixed_scope?: number | null; scope_change: number; qa_backlog_sp: number; days_remaining?: number | null; current_velocity: number; estimated_days_required?: number | null; forecast_status: string; health: { status: string; reasons: string[] } }

const tone: Record<string, string> = { HEALTHY: 'bg-green-100 text-green-800', 'AT RISK': 'bg-amber-100 text-amber-800', CRITICAL: 'bg-red-100 text-red-800', UNKNOWN: 'bg-gray-100 text-gray-700' }

export default function Analytics() {
  const [data, setData] = useState<AnalyticsData | null>(null)
  useEffect(() => { api.get('/analytics/summary').then(({ data: response }) => setData(response)) }, [])
  if (!data) return <div className="card">Loading analytics...</div>
  if (!data.has_data) return <div className="card"><h1 className="text-2xl font-bold">Analytics</h1><p className="mt-2 text-gray-600">Generate a snapshot to unlock sprint analytics.</p></div>
  return <div className="space-y-6"><div><p className="text-sm uppercase tracking-wide text-gray-500">Decision support</p><h1 className="text-3xl font-bold text-gray-900">Sprint Analytics</h1><p className="mt-1 text-gray-600">{data.sprint} · estimates are based on persisted snapshots.</p></div><div className="card flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-gray-500">Sprint health</p><p className="mt-1 text-2xl font-bold">{data.health.status}</p></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${tone[data.health.status] || tone.UNKNOWN}`}>{data.health.status}</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><div className="card"><p className="text-sm text-gray-500">Completion</p><p className="text-2xl font-bold">{data.completion_pct.toFixed(2)}%</p></div><div className="card"><p className="text-sm text-gray-500">Remaining SP</p><p className="text-2xl font-bold">{data.remaining_sp.toFixed(2)}</p></div><div className="card"><p className="text-sm text-gray-500">Current velocity</p><p className="text-2xl font-bold">{data.current_velocity.toFixed(2)} SP/day</p></div><div className="card"><p className="text-sm text-gray-500">QA backlog</p><p className="text-2xl font-bold">{data.qa_backlog_sp.toFixed(2)} SP</p></div></div><div className="grid lg:grid-cols-2 gap-6"><div className="card"><h2 className="text-xl font-semibold">Why this status?</h2><ul className="mt-4 space-y-3">{data.health.reasons.map((reason) => <li key={reason} className="flex gap-2 text-gray-700"><span className="text-brand-mid">•</span>{reason}</li>)}</ul></div><div className="card"><h2 className="text-xl font-semibold">Forecast</h2><div className="mt-4 space-y-3 text-sm"><p>Days remaining <strong className="float-right">{data.days_remaining ?? 'N/A'}</strong></p><p>Estimated days required <strong className="float-right">{data.estimated_days_required?.toFixed(2) ?? 'N/A'}</strong></p><p>Scope change <strong className="float-right">{data.scope_change >= 0 ? '+' : ''}{data.scope_change.toFixed(2)} SP</strong></p><p className="border-t pt-3">Forecast status <strong className="float-right">{data.forecast_status === 'MAY_MISS' ? 'May miss sprint target' : 'On track'}</strong></p></div></div></div></div>
}